services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    command: ["python", "manage.py", "runserver", "0.0.0.0:${PORT}"]
  
  react:
    build: ./DeafLearning
    ports:
      - "3000:3000"
    volumes:
      - ./DeafLearning:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
  
  flask:
    build: ./DeafLearning/app
    ports:
      - "5000:5000"
    volumes:
      - ./DeafLearning/app:/app
    environment:
      - FLASK_APP=app.py
    command: ["python", "app.py"] 