# Generated by Django 5.1.6 on 2025-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_score', models.FloatField()),
                ('fluency_score', models.FloatField()),
                ('completeness_score', models.FloatField()),
                ('pronunciation_score', models.FloatField()),
                ('errors', models.JSONField(default=list)),
            ],
        ),
    ]
